---
title: The role of the superior colliculus in more complex movements

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Bonnie Cooper
    affiliation: a
  - name: Robert M McPeek
    affiliation: a
address:
  - code: a
    address: SUNY College of Optometry, Department of Biological Science, 33 West 42nd St, New York, NY, 11206


corresponding_author:
  - code: 2
    text: "To whom correspondence should be addressed. E-mail: bob@email.com"

# For footer text
lead_author_surname: Cooper

## Remove this if not required    
equal_authors:
  - code: 1
    text: "A.O.(Author One) and A.T. (Author Two) contributed equally to this work (remove if not applicable)."


author_contributions: |
  The authors banged thier heads against a wall during a pandemic to produce this.

## Remove this if not required
conflict_of_interest: |
  We have no conflict of interest to report

abstract: |
  The superior colliculus (SC) has a long and storied role as testbed for the neural control of eye-movements. It was over seventy years ago that Apter demonstrated the orderly mapping of saccade vectors to corresponding locations in the visual field of the colliculus in cat. Since then, there have been numerous high-impact studies to manipulate the orderly relationship between visuotopic space and saccade vector across SC topography in an effort to better uderstand the physiological underpinnings of the sensorimotor signal transformation. However, less attention has been paid to the other motor responses associated with SC activity that range in complexity from concerted movements of muscle groups (e.g. coordinated saccades and head movements) to behaviors that involve whole body plan movement sequences such as fight or flight responses in murine models. This review attempts to survey complex movements associated with SC activity (optic-tectum in non-mammalian species) and, where possible, provide a philogenetic and ethological perspective for context.


significance: |
  The superior colliculus (SC) is a well studied area of the midbrain that integrates sensory information to guide behavioral responses to stimuli in an animals environment. In structure, the SC is remarkably well preserved across phyllum. However, the behavioral responses guided by SC activity vary widely across animal species. This review attempts to place the basic underlying structure of the SC in the phylogenetic and ethological context of a model animal to emphasive a more broader role SC plays than is usually considered. While it is true that the SC serves as a key node in the neural circuitry that guides saccades in primates, the SC, more generally, has a role in guiding orienting behaviors to facilitate an animals appropriate reaction to stimuli in the environment.

acknowledgements: |
  Who should we send this for comments? Rob, you had mentioned someone that you wanted to write a section, but I've long since forgotten.

keywords:
  - superior colluculus
  - movement
  - vision
  - sensorimotor
  - phylogenetic



## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle

bibliography: complexSC.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

output: rticles::pnas_article
---

In mammals, the superior colliculus (SC) is a small pair of structures situated on the roof of the midbrain underneath the thalamus. The midbrain is thought to have evolved to give sensory inputs from the forebrain influence over fixed action pattern generators to guide behaviors such as locomotion, grasping and orienting; the later of which SC has a prominent role [@schneider2014brain]. Indeed, the earliest observed motor responses elicited by SC were saccades which orient the eyes towards visual stimuli. Saccades were evoked by microstimulation in early experiments with cats [@adamuk1870dieinnervation], later inhibited by chemical ablation [@apter1946eye]. Aptner's early work in cat SC was sigificant because it detailed the orderly spatial relationship of the movement of the eyes towards a particular area of the visual field. From this work followed a series of influential physiology papers that demonstrated the same topographcal relationship in macaque [@robinson1972eye; @schiller1972single]. Furthermore, the distinctions between the SC’s visual receptive and motor fields [@goldberg1972activity], thier orderly retinotopic mapping [@wurtz1971superior; @robinson1972eye], and correspondence in visual space [@schiller1972single]. SC topography allows the spatial relations and behavioral context of stimuli to be manipulated with relative ease to better understand the neural representations of the stimuli, the decision process that govern responses, the motor commands that execute said responses as well as various effects of attention or other internal states (for review @basso2017circuits). A result of this orderly relationship of sensory inputs to saccade vector, in the primate, much attention has been paid to the sensorimotor transformation to guide saccades [@wurtz1980visual].  

While much of SC research has focused on saccades, many other more complex orienting response patterns have been observed. A remarkable conservation of function across phylogeny [@sparks1988neural; @kaas1997topographic] has been demonstrated in SC's involvement in orienting toward novel stimuli in species as diverse as rats and hamsters [@mchaffie1982eye; @mort1980role; @goodale1975effects], rabbits and cat [@schaefer1970unit; @harris1980superior; @roucoux1980stimulation; @munoz1989fixation], bat [@valentine2002orienting], as well as the optic tectum of goldfish [@herrero1998tail], zebrafish [@bianco2015visuomotor], and lower vertebrates such as the lamprey [@saitoh2007tectal]. For many of the early stimulation studies, with increasing stimulation intensity or duration came increasing response movement complexity as in rodents [@dean1989event] and cat [@harris1980superior]. Studies in primates can yield complex orienting behaviors such as combined eye-head gaze shifts [@cowie1994subcortical; @freedman1996combined] and reaching behaviors [@werner1993neurons; @stuphorn2000neurons]. However, the correspondence of increasing behavioral complexity with stimulation intensity observed in other animal systems (e.g. aversive flight behaviors observed in murine models), are muted or seemingly absent in the primate.    

Why would behavioral responses guided by SC, a well conserved structure, be so different in the primate? The intent of this review is to place the primate SC in a behavioral and phylogenetic context to understand why the primate SC is hyper-specialized for saccade guidance with a lesser role in more complex movements. 

Basic SC Blueprint {.unnumbered}
========================================

Understanding the architecture of SC lends insight to understanding SC function. The SC is a multi-layered structure with unique anatomical, morphological & functional distinctions between the layers [@may2006mammalian; @white2011superior]. Superficial SC layers receive contralateral visual inputs that arrive either directly from the retina via the retinotectal pathway or indirectly from V1 and other visual cortical areas @boehnke2008importance. Visual information projects in an orderly retinotopic mapping to the surface of the contralateral SC and this pattern is a constant and conserved across vertebrate phylogeny [@stein1981organization; @schneider2014brain]. Orderly mappings of the visual field have been demonstrated in the SC (and optic tectum of non-mammals) across many mammal, avian, fish and amphibian species, they each present with their own idiosyncrasies. The distribution of visual projections to colliculus are a prime example of mosaic evolution and vary in several species-specific ways. First, the relative size and cross-sectional diameter of SC varies between species. For example, the relative sizes of SC and inferior colliculus (IC) differs in highly visual mammals compared to echolocating mammals (Fig 1). Highly visual mammals such as the ibex and the tarsier have larger SC structures, whereas echolocating mammals such as the bat and dolphin, which rely more heavily on auditory sensory signals, have larger IC than SC structures. Secondly, SC’s of different species have different ratios of retinotectal to retino-thalamic-cortical visual inputs. For example, rodents have a comparatively high proportion of retinotectal inputs compared to primates @schneider2014brain. Third, SC topography is inherited from the retinotopy and this mapping of visual inputs in SC can be related to orienting behaviors. For example, some species have evolved retinal regions of high retinal ganglion cell density such as the primate fovea, or the visual streak of cats [@hughes1977topography] this over-representation of regions of the visual field translates to a magnification of representation of visual field space across SC's visual input mappings. Figure 2 compares the topography of visual inputs to rat and cat SC. Rodents retina has a relatively evenly sampled retinal ganglion cell mosaic and, therefore, rat SC presents with a reasonably linear mapping of the visual field. On the other hand, the cat has a pronounced 'visual streak' in the central region of the visual field [@hughes1975quantitative], therefore the feline SC inherits a magnification of the central visual field. The primate retina has a similar over-representation of central visual field inherited from the parafovea [@cynader1972receptive; @ottes1986visuomotor] and with a fovial magnification factor comparable to that of V1 in the cortex [@chen2019foveal]. Eye movements are ecologically important behaviors, because orienting the region of the eye with the greatest photoreceptor density is optimal for extracting information. However, for animals with a relatively even spacing of the retinal photoreceptors, such as rodents, saccades are of less utility.

![View of the midbrain from four representative mammals: a bat and dolphin (top row: two echolocating mammals) and the idex and tarsier (bottom row: two mammals that rely heavily on vision). The SC's main sensory input projects from the retina while the IC recieves primarily auditory input; this figure illustrates mosaic evolution of SC/IC sensory representation (from [@schneider2014brain] pg110).<span data-label="fig:schnieder"></span>](schniederFig.png)

![Topography of visual projections to the superficial layer of rat (top) and cat (bottom) SC. In both species, lateral SC represents ventral, medial SC represents dorsal, anterior SC represents nasal and the posterior SC represents tenmporal visual field. However, in the cat, there is a noticeable magnification of the central visual fields. A similar magnification is found in the primate SC (reproduced from [@stein1981organization].<span data-label="fig:stein"></span>](steinScaled.png)


The intermediate and deep layers of the SC recieve inputs that are comparatively more diverse than the superficial layer. Numerous sensory inputs combine with projections from prefrontal cortex, parietal cortex and subcortical projections [@schneider2014brain; @white2011superior]. The sensory input to intermediate layers from higher cortical centers is a multimodal visual, auditory and somatosensory information that combines with the direct input from the SC’s superficial layer @meredith1986visual. In effect, the superficial layer’s representation of visual space is integrated with a corresponding map of auditory, somatosensory signals and additional visual information (most likely from cortical visual areas) in the deeper layers to create a multimodal priority map to better guide behavioral responses [@drager1975responses, @meredith1986visual; @king2004superior]. This multimodal sensory representation may serve to support the phenomenon of multisensory facilitation, where synchronous spatial and temporal stimuli from disparate sensory modalities can combine to enhance detection [@welch1986contributions; @stein1993merging]. Multisensory facilitation has been demonstrated in SC response properties of several mammals including the cat and primate [@wallace1996representation]. Furthermore, lesions to SC in the cat were shown to preferentially disrupt a cats ability to perform a multisensory orientation task @burnett2004superior. After a period of recovery from unilateral SC lesions, cats were able to perform visual or auditory tasks at pre-lesion performance levels. However, performance on tasks that combine visual and auditory stimuli lacked multisensory facilitation effects. Thus, SC’s merging of sensory maps has a role in the optimization of complex orienting responses to environmental stimuli. 

Apart from sensory information, intermediate and deep layers of the colliculus are densely interconnected with a network of cortical areas that guide orienting movements such as saccades. In the primate, this includes but is not limited to the Frontal Eye Fields (FEF) and the Supplementary Eye Fields (SEF) of the Prefrontal Cortex (PFC), the Lateral Intraparietal area (LIP) in parietal cortex, the cingulate cortex and the Substantia Nigra (SNr) in the Basal Ganglia [@platt2003situating]. Like SC, FEF integrates visual sensory input and is a key cortical area for guiding saccades in primates [@hanes2001interaction; @schall1999neural; @schall2002neural]; signals of FEF activity convey a covert motor preparation, or priority signal for planning saccades. The SEF is thought to integrate anticipation and behaviorally relevant goals as context for the decision process of where to direct orientation movements/ allocate attention resources [@schall1991neuronal; @roesch2003impact]. LIP propogates signals that descibe the salience of potential targets; this area interconnects with SC directly and via projections to FEF [@gottlieb1998representation; @goldberg2006saccades]. The cingulate cortex does not directly guide saccades, however, it is observed to monitor the expected and reward outcome of sensorimotor decisions [@carter1998anterior; @ito2003performance]. SNr has a facinating role in goal-directed orienting behaviors; populations of SNr GABAergic neurons control the initiation of saccades by modulating disinhibition of SC activity and are further influenced by reward-dependant SNr dopaminergic neurons [@hikosaka2000role; @hikosaka2007basal]. Collectively these areas work as a circuit to build a behaviorally relevant representation of priority for potential locations in the visual field and to allocate attention and or orienting behaviors. Within this network, SC acts as a primary gateway for a final saccade goals [@fecteau2006salience; @bisley2019neural]

SC forms dense interconnections with cortical circuitry to guide orienting behaviors. SC is set apart and unique from it's partner nodes in this circuit because of it's proximity in the midbrain and stronger direct connectivity to the brainstem oculomotor nuclei that isue the motor commants that ultimately execute behavioral responses. Most descending motor output of the deep SC projects to the brainsten saccadic circuits located in the pons and reticular formation which control the vertical and horizontal components of saccades. In addition to oculomotor nuclei, the SC also sends projections to the spinal cord. In many mammals, these pathways lead to cervical spinal chord and are involved in head movements [@may2006mammalian]. Cats are found to have many tectal projections to cervials spinal chord whereas primates have been found to have less. This has lead to speculation that the SC might actually be encoding gaze-related information rather than saccade vectors [@freedman1997eye; @sparks200412]

The intermediate and deep layers of SC receive a confluence of inputs from as many as 40 different cortical and subcortical projections [@edwards1979sources; @huerta1984connectional]. Understanding the role for this variety, is facilitated by an appreciation for the phylogenetic wiring principles of the brain. For rudimentary chordates, orienting behaviors were limited. Sensory information was relayed directly to the hindbrain and if a noxious stimulus was detected and an escape behavior was triggered via descending uncrossed pathways. The midbrain likely evolved to allow more recently developed sensory modalities to integrate with the existing infrastructure and ultimately guide behavioral responses. Speed is of the essence. Particularly when survival in the wild hinges on reacting to novel stimuli. One could speculate that for the most primitive of visual systems, the fastest way (least synapses) for a sensory signal to affect a motor pathway requires crossed projections of visual information to midbrain and on to the descending uncrossed pathways; such a connection would facilitate a faster contraction along the contralateral side of the organism resulting in an expedited aversive reaction away from a stimulus. In time, as sensory capabilities developed further and optical image formation became a thing, an orderly mapping of sensory representation could be utilized to guide more refined orienting behaviors. As a result, the contralateral SC mapping decussates projections to form the crossed tectofugal pathways that guide orienting behaviors towards environmental stimuli [@schneider2014brain]; hence, this pathway takes a circuitous route to guide ipsilateral orienting movements towards a stimulus. This concept is supported by recent work in the optic tectum of the lamprey where GABAergic interneurons were found to mediate a switch to generate opposing orienting or evasion behaviors [@saitoh2007tectal; @suzuki2019role]. 

![A) A schematic showing the visual field quadrants of the lamprey retina with the corresponding representation projected on the superficial layer of the optictectum. For the lamprey, the central visual field follows a different pathway (axial optic tract) to the pretectum (image from @cornide2011retinotopy). B) Tectal circuitry that guides visual behavior in the Lamprey: visual signals from the retina activate distinct neuronal cell classes (coBP and iBP) which ultimately project to motorneurons on opposite sides of the body to guide either approach or avoidance behaviors (image from [@suzuki2019role]).<span data-label="fig:grillner"></span>](lampreyFigScaled.png)

Optic Tectum of a Living Fossil {.unnumbered}
========================================

The lamprey is a representative species of the superclass Cyclostomata, the most ancient group of extant vertebrates [@yang2016lamprey]. Lampreys and related jawless fish have long been considered 'living fossils' and the direct ancestors to other modern vertebrates. Lamprey anatomy has remained relatively unchanged for hundreds of millions of years [@gess2006lamprey] and therefore have been used as model organisms to study vertebrate evolution, development and more [@nikitina2009sea; @green2014lamprey; @mccauley2015lampreys; @yang2016lamprey]. Although lampreys hold the most basal ranking and are thought to have diverged from vertebrates phylogeny as long as 550 million years ago [@kumar1998molecular], the lamprey optic tectum remarkably shares many anatomical and physiological similarities with the superior colliculus of modern mammals making them an attractive model system to investigate the midbrain sensorimotor transformation. This section descibes the lamprey optic tectum in further detail to give context to the optic tectum and to the superior colliculus of mammals having a role in guiding complex movements as behavioral responses.

As in other vertebrates, the superficial layer of the lamprey optic tectum recieves afferent visual input from the retina [@kosareva1980retinal; @kennedy1977retinal]. While the lamprey pallium, a primitive protocortex, does recieve visual input with a retinotopic mapping [@suryanarayana2017lamprey; @suryanarayana2020evolutionary], the pallium is relatively underdeveled in jawless fish and so the midbrain recieves the bulkwork of retinal projections. Lamprey retinotectal projections follow two main pathways: the axial optic tract carries afferents from the central visual field to the pretectum and has been implicated in visual escape behaviors. The lateral optic tract projects a retinotopic mapping of the lateral retina to the optic tectum and has been associated with goal orienting behaviors [@jones2009selective; @cornide2011retinotopy]. The axial and lateral optic tracts are found to synapse with specific subsets of retinal ganglion cells which follow different temporal development patterns as lamprey larvae mature with the lateral projections to the optic tectum establishing much later during development [@cornide2011retinotopy]. Retinotopic visual signals in the superficial layer are further shaped by GABAergic lateral connections [@kardamakis2015tectal] which suppress extraneous activity across optic tectum retinotopy to reduce competition once a target has been detected. Therefor, while significant embiogenesis differences exist, the superficial optic tectum of the lamprey receives a retinotopic mapping of salience across visual space much like other vertebrates (Fig 3A).

As in the case with higher vertebrates, the nature of the inputs to intermediate and deep optic tectum layers increases in complexity. For example, the octavolateral area in the hindbrain recieves electrosensory afferents from the lateral line nerve [@bodznick1981electroreception]. Octavolateral input projects to the intermediate layer of the optic tectum and is combined with superficial layer's visual signals in the deep layer to build a multimodal sensory representation of the environment. The integrated multisensory input in the optic tectum has been shown to independently enhance responses to guide event-detection [@kardamakis2016spatiotemporal]; this is significant because, that vetebrates as primative as the lamprey multiplex sensory information in the optic tectum to guide motor responses, it sets a precedence for multisensory representations in the mammallian superior colliculus. In addition to sensory input, the intermediate layer recieves inputs from other areas including the forebrain and tonic inhibition via the basal ganglia [@robertson2006afferents]. The deep layer of the lamprey optic tecum integrates information from overlying layers unto two classes of output neurons that either descend ipsilatterally (iBP neurons) or decussate and cross to the contrallateral side (coBP neurons) of the brainstem. Stimulation of the of the optic tectum produces an orderly topographic output of various eye-body motor responses. Additionally, the lamprey is capable of horizontal eye-movements and a pattern for tectal oculomotor mapping has been described however, it is not as refined as in other vetebrate systems [@saitoh2007tectal]. The work of Grillnor and collaborators describes how the neural circuit of the optic tectum integrates sensory information and acts as a switch to guide behavior via the two distinct descending pathways for either evasive escape behaviors (iBP) or orienting behaviors (coBP) given the appropriate sensory input [@suzuki2019role] (Fig 3B).

Grillner and collaborators have developed a unique preparations that allows them to present visual stimuli and deliver phamacological agents while simultaneously recordings from the optic tectum, reticulospinal neurons, and/or the ventral roots [@kardamakis2015tectal]. This has allowed them them to methodically probe the optic tectum microcircuitry to understand the integration of sensory information across the superficial layer while mechanisms of the intermediate and deep layers integrate multimodal sensory signals and, due to preferential selectivity to stimulus properties, act as a switch to guide appropriate behavioral responses. By modulating properties of looming stimuli with a unique eye-brain-spinal cord preparation, Grillner et al demonstrated that local inhibitory neurons in superficial optic tectum are responsible for selecting for downstream signaling via distinct classes of neurons in deep layers of the tectum. Fast moving dots or bars that simulate the approach of a predator, preferentially activated iBP neurons resulting in escape/evasion behaviors. In comparison, slow looming dots preferentially activated the coBP neurons to guide orienting behaviors. coBP neurons were activated by relatively weaker stimuli than iBP possibly owing to stronger effects of lateral inhibition for slower looming stimui. Additionally, coBP and iBP neurons select for stimuli by mapping the optic tectum surface differently. iBP neurons tile the optic tectum with a relatively even mosaic. On the other hand, coBP neurons are concentrated on the anterior tectum representing the anterior visual field, therefore the lamprey is biased towards escape movements for posterior visual field stimuli and has the most information to switch between orienting or escape behaviors for anterior stimuli. This finding is significant, because, due to the highly concerved nature of the optic tectum (superior colliculus), a similar switching mechanism might be supported in higher vertebrates.

![Topography of vectors evoked from saccades in the common goldfish, a teleost fish (*Carassius
auratus*), (image from [@salas1997tectal]).<span data-label="fig:salas"></span>](salasScaled.png)

Emergence of Eye-movements and the Optic Tectum {.unnumbered}
========================================

The optic tectum of teleost fishes marks an advancement in similarity towards the superior colliculus of mammals in part because a more sophisticated topography of eye-movements emerges [@land2015eye]. In the lamprey, the motor responses elicited from optic tectum are generally coordinated eye, head and/or body movements, but, experimental use of brief, low-voltage stimulation may elicit isolated eye-movements. However, because lampreys are only capable of horizontal eye-movements, the topography is muted: contralateral eye-movement amplitudes decrease from the lateral and caudal extremes of the tectum towards the medial tectum where both contraversive and ipsiversive eye-movements were observed [@saitoh2007tectal]. In comparison, the teleost fishes have more developed ocular musculature and are therefore capable of increasingly complex eye-movements [@graf1978eye, @torres1992afferents, @northmore2011optic]. This advancement is reflected in the eye-movement topography of optic tectum.  

The topography of the teleost optic tectum to guiding eye-movements and orienting behaviors were first demonstrated in the common goldfish [@salas1997tectal]. Electrical stimulation of the goldfish optic tectum yielded a detailed topographic mapping of saccade vectors (Fig 4). Saccade direction was found to change vertically from upwards to downwards in terms of the visual field along the mediolateral axis, while saccade amplitude increased towards the anteroposterior tectum. Additionally, functional zones subdividing the tectum were described. For example, the medial tectal zone reorients gaze to an area of the visual field with a combination of eye and postural movements, the antero-lateral zones are typified by goal directed eye and body movements, whereas the posterior zone of the tectum is elicit distinct tail and fin-erection to produce backing and turning movements associated with escape-like behaviors [@torres2005visual, @herrero1998tail]. Another feature reminiscent of the lamprey, many tectal sites elicited stimulus dependant behavioral responses [@herrero1998tail]. Low current stimulation to the rostal tectum typically resulted in movements characterized as orienting behaviors. On the other hand, relatively higher current strengths to the intermediate and deep layers of posterior tectal sites elicited escape behaviors, and this is intuitively advantageous to the animal to treat a peripheral stimulus from behind (activating the poserior tectum) as a potential threat. These findings are significant, because the superimpose saccade vector topography over an established lamprey-like behavioral switching mechanism in teleost tectum.  

A similar pattern of tectal guidance for stimulus dependent and distinct orient-towards or escape-away behavioral responses has been described in the zebrafish danio, *Danio rerio*. The zebrafish has proven advantageous for studying applications of visual neuroscience because it is a genetic model orgnaism and this allows for more refined manipulations of the tectal circuitry [@bilotta2001zebrafish, @mcarthur2020zebrafish]. Zebrafish orient towards and pursue small moving stimuli whereas large, looming stimuli elcit escape behaviors [@bianco2011prey, temizer2015visual, @dunn2016neural] and this has been used as a behavioral paradigm to study the sensorimotor transformation across the optic tectum. Barker & Baier (2015) manipulated stimulus size while combining calcium imaging, pharmacogenetic lesions and optogenetic approaches to show a distinct class of tectal neurons bias approach behaviors [@barker2015sensorimotor]. GAL4 enhancer trapping methods were used to create different genetic ablations to the tectum [@scott2007targeting]. Gal4s1156t lines labelled and ablated GABAergic superificial tectal interneurons which a critial for lateral inhibition and in the zebrafish may play a role in stimulus size representation [@preuss2014classification]. As a result, these fish had particularly large behavioral response deficits for large stimuli and were biased against escape behaviors. However, Gal4s1156t ablated fish presented with general lack of behavioral responsiveness. In comparison, Gal4mn354 ablations targeted a specific subset of interneurons (nsPVIN) restricted to the dorsal tectum [@nevin2010focusing] whose absense resulted in orienting behavior deficits. Furthermore, optogenetic activation of GAL4mn354 labelled cells facilitated orienting and approach behaviors. Taken together, this supports a role for GAL4mn354 labelled nsPVIN neurons as a distinct pathway mediating orienting behaviors. These findings suggest a role for the superficial optic tectum in filtering visual input to lend context that biases behavior whereas deeper interneurons may serve to switch between appropriate motor responses.  

In recent work, Helmbrecht *et al.* further establish distinct descending tectal pathways that serve as 'labelled-lines' to mediate appropriate behavioral responses [@helmbrecht2018topography]. Genetic single cell labelling techniques were used to selectively label tectofugal neurons and trace output pathways [@scott2007targeting] to visualize a tectal projectome and at least seven pathways topographically organized across the tectum. Of the seven, the ipsilateral tectobulbar tract (iTB) consistently showed a division of behavioral function with medial iTB (iTB-M) afferents responding primarily to larger looming stimuli and lateral units (iTB-L) selective for smaller prey-like stimuli. Furthermore, the medial and lateral iTB projections were found to connect morphologically distinct classes of cells. Optogenetic, calcium imaging and behavioral tracking methods were used to find that sensory information to guide approach behaviors via the iTB-L pathway follow an orderly topography along the anterior to posterior axes suggesting that functional responses reflect the spatial location of stimuli resembling potential prey. However, this was not the case with looming visual stimuli. The signal mediating escape behaviors via the iTB-M are localized to the posterior visual field (Fig 5). These findings are significant because it demostrates that specific visual stimuli are filtered at the level of the optic tectum and directed across parallel labelled-lines to distinct targets in the brainstem to guide behaviorally relevant responses. This suggests a broad role for the teleost optic tectum in forming fly-by-wire representations from primarily visual, but integrating other sensory information as well, transformed to body-centric representation that is selectively channeled to specific targets in brainstem motor centers to effect appropriate behavioral responses [@northmore2011optic]. Helmbrecht *et al.* observed uncrossed ipselateral tectofugal pathways to switch between orienting and escaping behaviors, however, different circuitry has been suggested in the superior colliculus of the rodents brain. This discussion will be taken up in the following section.

![Tectofugal sensorimotor decision pathways that mediate avoidance behaviors in response to looming targets via iTB-M pathway (left panel) and approach behaviors for smaller targets via iTB-L pathway (right panel), (image from [@helmbrecht2018topography]).<span data-label="fig:salas"></span>](zebrafish.png)


Complex Movements and the Murine Superior Colliculus {.unnumbered}
========================================

Mammals may have evolved high-resolution senses, complex motor systems and nuanced cognitive capabilities, however, they inherited some basic neural wiring principles from the early vertebrates and this is made apparent in SC, a well conserved and phylogenetically ancient region of the brain [@butler2008evolution, @schneider2014brain]. Early electrophysiology experiments in the superior colliculus of mammals yielded perplexing results to investigators. How could the same structure that presents with an orderly retinotopic mapping and underlying motor map of saccade vectors also elicit seemingly contradictory movement patterns when higher levels of stimulation voltage applied? For example, (I.e. orienting toward and escape away from novel stimuli).  find a context in parallel with the lamprey optic tectum. The work of Redgrave and colleagues have described two distinct collicular response systems that subdivide output projections across the midline into crossed and uncrossed descending pathways (Dean1989).  

In a series of experiments, Redgrave et al manipulated collicular microcircuitry by administering GABA blockers and observed complex aversive behaviors that resembled flight. “SC has access to a large family of defense-related ‘fight-or-flight' reactions and is capable of producing a fully integrated response when appropriately triggered.” A systematic mapping of the behaviors elicited from stimulation sites revealed distinct subregions of murine colliculus or a ‘functional mosaic’: lateral superficial and intermediate cites generally yielded innitial behavioral responses that could be described as defensive and ‘cringlike’, whereas cites that lay in deeper layers yielded contralateral orienting movements (Sahibzada 1986). Furthermore, a retrograde tracing study revealed that specific regions of murine colliculus send the predominant proportions of their projections across distinct descending pathways: ipsilateral CNF projections are located in medial colliculus and correspond with upper visual field whereas contralateral PDB projections are found in intermediate and deep layers (Redgrave et al1987). Westby et al show that the previously described regions receive distinct sensory contribution (Westby 1990) Taken together, distinct pathways of murine superior colliculus were found to receive distinct sensory inputs, mediate distinct behavioral responses, and send downstream projections across segregated crossed and uncrossed pathways.  

A growing body of work in rodents suggests a more generalized role for the superior colliculus in sensory based decision processes to guide appropriate behavioral responses to novel environmental stimuli (Redgrave). The rodent SC has been shown to guide both orienting responses towards a novel stimulus as well as defensive aversion behaviors away from a stimulus; these responses seem opposed to each other. Furthermore, if a defensive behavior is warranted, specific regions of the SC have a more prominent role in freezing behavior whereas others elicit flight or rapid evasion behaviors. (Redgrave, Dean papers) The complex and contrasting behaviors observed in murine studies seem to challenge the predominant role of primate SC in guiding eye movements to visual targets. However, when the connectivity and architecture of SC is considered through both an ethological and phylogenetic lens, we begin to understand the specialization of the primate SC in context. Here we attempt to bridge this subject.   

!! include somewhere the iTB/cTB discrepancy between zebrafish findings and thoughts on rodents
!! Rephrase here: Eye movements are ecologically important behaviors, because orienting the region of the eye with the greatest photoreceptor density is optimal for extracting information. However, for animals with a relatively even spacing of the retinal photoreceptors, such as rodents, saccades are of less utility. !! But rats get a higher proportion of retinotectal projections than other mammals. So if eye-movements arent as important for rodents, what behaviors does rodent SC encourage/support


Guide to using this template {.unnumbered}
========================================

SC binds multimodal sensory input with cognitive factors and bridges the signals to stereotyped response generators that can immediately trigger complex movement plans for the most appropriate response to a novel stimulus. Redgrave systematically studied SC topography and found that stimulation in distinct regions of SC yielded specific behavior response patterns and that the response also depended on the nature of the stimulus. (Figure 7A from Dean 1989) 

 

Decision rules: having two pathways raises the problem of how the right one is chosen. What are the decision rules that specify which response is initiated by the SC? Sometimes a simple rule like position of the stimulus in the visual field: unexpected movement from overhead is more likely to produce flight whereas movement in the lower field is more likely to produce approach behavior. Redgrave Basal ganglia paper 1999 

 

 

The second example differentiates between fight or flight. In mice this translates to freeze or flea. Something interesting about the nature of many of these inputs is that they are not evenly distributed across SC topography. Rather, they have been described as ‘patches or puffs’. This hints at a specificity that could be significant to function/behavioral outcomes. 

Patches puffs clusters modules Sparks & Hartwich-Young 1989 

Bittencort defensive behaviors stimulation & chemical in rat 

Shang. Rally cool very recent study that outlines the specific neural pathways for flight vs freeze behavior. 

Shang, Congping, et al. "Divergent midbrain circuits orchestrate escape and freezing responses to looming stimuli in mice." Nature communications 9.1 (2018): 1232. 

SC orchestrates dimorphic defensive behaviors (escape or freeze) through two separate tectofugal pathways that may have interactions. 

A subset of (SC) neurons may detect looming visual stimuli and participate in the generation of dimorphic defensive behaviors. However, the identity of these looming detectors and their downstream neural circuits to orchestrate innate defensive behaviors is poorly defined. 

This study examines the roles of (PV+) neurons and their divergent downstream pathways in visually triggered defensive behaviors...Do SC PV+ neurons participate in coordinating the action selection between fleeing and freezing...This study indicates that the SC PV+ neurons orchestrate dimorphic defensive behaviors with two divergent tectofugal visual pathways. 

Two distinct groups of PV+ neurons formed divergent visual pathways to the PBGN and LPTN, respectively....a dual-circuit winner-take-all mechanism used to orchestrate dimorphic defensive behaviors in mammals. Data presented in this study indicates the that these two apparently redundant pathways (SC-LPTN-LA & PV+ SC-PBGN) co-exist in the mouse brain and differentially contribute to distinct defensive behavioral patterns triggered by looming visual stimuli. 

Behavioral context: a shelter in an arena is more likely to induce escape behaviors. Whereas the passing of an overhead shadow overhead is more likely to induce freezing behavior. 

PV+ SC neurons: predominantly distributed in the retinal recipient layers (superficial). Most SC PV+ neurons are glutaminergic. 

Effects of SC PV+ neuron inactivation on visually triggered defensive behaviors: are essential for both Type 1 & 2 defensive behavioral patterns. 

How SC PV+ neurons mediate both type 1 & 2 defensive behavioral patterns: whole brain mapping & found 6 projection areas. In addition to the SC PV+ -> PBGN, there was also a notable connection of SC PV+ -> LPTN which previous studies had indicated involvement with fear responses. Retrograde tracing results indicate the there may be different populations of SC PV+ neurons that make connections to PBGN or LPTN. Both PBGN & LPTN receive threat-relevant visual signals from SC PV+ neurons. Optogenetic activation of the PV+ SC->PBGN pathway triggered impulsive escape followed by long-lasting freezing whereas activation of the PV+ SC->LPTN pathway induced immediate freezing; this roughly mimicked the dimorphic defensive behaviors triggered by looming visual stimuli. 

Selectively silencing PBGN or LPTN: synaptic inactivation of the bilateral PBGN resulted in the disappearance of the Type1 defensive behavioral pattern & dominance of type2 pattern. Conversely, bilateral LPTN inactivation showed the type1 behavior pattern. This suggests that PBGN and LPTN mutually compete for the dominance of the behavioral outcome for Type1/2 in response to looming visual stimuli. 

Author Affiliations {#author-affiliations .unnumbered}
-------------------

Even more important for the survival of small preyed-upon animals (probably more primitive in evolutionary history) there are distinct outputs for triggering movements of fleeing or freezing. The escape movements are the function of uncrossed descending pathways from the midbrain tectum, whereas orienting movements are the function of the crossed tectospinal tract. Schneider 

Functional mosaic: extensive inputs to intermediate & deep SC. Functional heterogeneity: inputs are not even across depth or topography. Patchy! As are collicular outputs: the descending projections of the SC seem therefore to be organized into anatomically distinct output channels. Redgrave 

Another example worth exploring: Vibrissae: an instance where different output projections have different inputs and that the nature of the inputs appears to be related to the function of the response that the corresponding output projection mediates (redgrave) 

Submitting Manuscripts {#submitting-manuscripts .unnumbered}
----------------------

Rambling points to spring off of for a conclusion: 

gotta cite Guitton somewhere.

I really like this sentence & want to broaden it : While the general problem of distinguishing emergency signal from neutral event is common to all species, the details of what counts as an emergency signal vary markedly between species.(redgrave) 

Redgrave: connections to basal ganglia 

In closing, Midbrain tectum is not given as much credit as the cortex when it comes to complex functions. The midbrain is often thought of more as a relay station to act as a gateway for converging cortical decision processes. However, the SC is a very complex structure that receives input from numerous areas (~40) that terminate in distinct depths of the SC. Additionally many of the terminations are not evenly homogenous; this suggests connections that segregated perhaps for specific & diverse functions. Research in primate SC has largely focused on orienting responses and allocation of attention. However, research in other vertebrates has revealed a much wider involvement in behaviors that mediate how an organism behaviorally reacts to stimuli in it’s environment. Some of the most revealing of this work has been in rodents. We review this here, followed by similar findings across other animals. 

Foveation hypothesis: the idea that the role of the neurons in the motor layers was to point the eyes towards the region of visual space encoded by the overlaying visual areas. Some of the earliest research in SC led to the foveation hypothesis. The bulkwork of SC research followed in this direction. 

So why then does primate SC focus on saccades? Because eye movements are so important to us to foveate and bring attention to stimuli so that our big cortex can properly analyze it. Primates are relatively high on the food chain, so don’t have the same need as rodents for looming detectors etc. 


<!-- Leave these lines as they are at the end of your .Rmd file to ensure placement of methods & acknowledgements sections before the references-->
\showmatmethods
\showacknow
\pnasbreak
